### ISSUE TITLE
Unable to Figure Out Configuration

### ISSUE THREAD

**Issue by ZachHandley** [2kewl4u/personal-roll-loot#1]
Hi! I followed the instructions but I'm unable to figure out how to configure it :\

Any advice?

**Comment by 2kewl4u** [comment]
hello and thanks for your request.

if you tell me what exactly you want to configure, i might be able to help. there will be a more detailed guide comming, until that, i hope that reading the description carefully might give u some insights.

kr

**Comment by ZachHandley** [comment]
I've read the description, but it tells me nothing on how to set it up. When I target a player in a raid or group that I'm lead of it doesn't do anything

**Comment by 2kewl4u** [comment]
i did update the description on curseforge. maybe this helps you with the setup.

**Comment by 2kewl4u** [comment]
you may reopen if something is still not clear. please provide more details about the configuration you would like to do. currently i have no plans to do a video... i'm really bad at it :)
